apiVersion: v1
kind: Pod
metadata:
  name: pod-sabri-c2-30 # name the pod what you like
  labels:
    app: app
spec:
  containers:
    - command:
        - sh
        - /pd/sabri/startup.sh # sleep forever so that the Pod doesn't die
      image: gcr.io/hai-gcp-fine-grained/default # replace this with whatever image you want
      name: pod-sabri
      resources:
        limits:
        requests:
      volumeMounts:
        - name: pv-1 # replace this with the name of the persistent volume you want to mount
          mountPath: /pd # this will mount the volume pv-1 at /home
        - name: dshm
          mountPath: /dev/shm
  volumes:
    - name: pv-1 # replace this with the name of the persistent volume you want to mount 
      persistentVolumeClaim:
        claimName: pvc-1 # replace this with the name of the persistent volume claim 
    - name: dshm
      emptyDir:
        medium: Memory
  restartPolicy: Never
  nodeSelector:
    # Make sure that your cluster actually has the accelerator you're requesting!
    cloud.google.com/gke-nodepool: c2-30 # or nvidia-tesla-p100 or nvidia-tesla-p4 or nvidia-tesla-v100 or nvidia-tesla-t4
