apiVersion: v1
kind: Pod
metadata:
  name: sabri-dev-pod # name the pod what you like
  labels:
    app: app
spec:
  containers:
    - command:
        - sh
        - /pd/sabri/startup.sh # sleep forever so that the Pod doesn't die
      image: gcr.io/hai-gcp-fine-grained/default # replace this with whatever image you want
      name: sabri-dev-pod
      resources:
        limits:
          memory: "2Gi"
        requests:
          memory: "2Gi"
      volumeMounts:
        - name: pv-2 # replace this with the name of the persistent volume you want to mount
          mountPath: /pd # this will mount the volume pv-1 at /home
        - name: pv-11 # replace this with the name of the persistent volume you want to mount
          mountPath: /pd11 # this will mount the volume pv-1 at /home
        - name: dshm
          mountPath: /dev/shm
      ports:
        - name: jupyter
          containerPort: 8000
        - name: streamlit
          containerPort: 8001
        - name: app
          containerPort: 8002
        - name: app-1
          containerPort: 8003
        - name: app-2
          containerPort: 8004
        - name: app-3
          containerPort: 8005
        - name: app-4
          containerPort: 8006
  volumes:
    - name: pv-2 # replace this with the name of the persistent volume you want to mount 
      persistentVolumeClaim:
        claimName: pvc-2 # replace this with the name of the persistent volume claim 
    - name: pv-11 # replace this with the name of the persistent volume you want to mount 
      persistentVolumeClaim:
        claimName: pvc-11 # replace this with the name of the persistent volume claim 
    - name: dshm
      emptyDir:
        medium: Memory
  restartPolicy: Never
  nodeSelector:
    # Make sure that your cluster actually has the accelerator you're requesting!
    cloud.google.com/gke-nodepool: dev 
