apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}

spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: {{ server_name }}