apiVersion: batch/v1
kind: Job
metadata:
  name: {{ job_name}}
spec:
    template:
        spec:
            containers:
                - command:
                    - sh
                    - /home/sabri/.startup
                image: gcr.io/hai-gcp-fine-grained/default # replace this with whatever image you want
            name: {{ pod_name }}
            resources:
                limits:
                memory: "2Gi"
                requests:
                memory: "2Gi"
            volumeMounts:
                {% for volume in volumes %}
                - name: {{ volume.pv_name }}
                mountPath: {{ volume.mount_path }}
                {% endfor %}
                - name: dshm
                mountPath: /dev/shm
            volumes:
                {% for volume in volumes %}
                - name: {{ volume.pv_name }}
                persistentVolumeClaim:
                    claimName: {{ volume.pvc_name }}
                {% endfor %}
                - name: dshm
                emptyDir:
                    medium: Memory
            restartPolicy: Never
            nodeSelector:
                # Make sure that your cluster actually has the accelerator you're requesting!
                cloud.google.com/gke-nodepool: {{ node_pool }} # replace this with the name of your node pool
backoffLimit: 0